version: '3.9'
services:
   database:
      container_name: notes-database
      image: postgres:14-alpine
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      volumes:
         - ./pgdata:/var/lib/postgresql/data
      networks:
         - notes-network

   backend:
      container_name: notes-backend
      build: .
      volumes:
         - .:/app
      ports:
         - 4000:4000
      networks:
         - notes-network
      depends_on:
         - database

networks:
   notes-network:
